routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('welcome');
Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('welcome');

Route::middleware('guest')
    ->group(function () {
        Auth::routes([
            'logout' => false,
            'register' => false,
            'confirm' => false,
            'verify' => false,
        ]);

        // Route::prefix('login')
        //     ->group(function () {
        //         Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');
        //         Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'login']);
        //     });

        // Route::prefix('register')
        //     ->group(function () {
        //         Route::get('/', [\App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
        //         Route::post('/', [\App\Http\Controllers\Auth\RegisterController::class, 'login']);
        //     });

        Route::prefix('register/ref/{referralUser}')
            ->name('registerReferral.')
            ->group(function () {
                // register.index => /register
                Route::get('/', [App\Http\Controllers\RegistrationController::class, 'index'])->name('index');
                // register.store => /register/store
                Route::post('/store', [App\Http\Controllers\RegistrationController::class, 'store'])->name('store');
            });
    });

Route::prefix('logout')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
        Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);
    });

Route::middleware('auth')
    ->group(function () {
        Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

        include('files/profile.php');
        include('files/password.php');
        include("files/package.php");
        include('files/dashboard.php');
        include('files/setting.php');
        include('files/member.php');
        include("files/bonus.php");
        include("files/withdraw.php");

        Route::middleware('auth.group:member')
            ->group(function () {
                include('files/network.php');
                include("files/bank.php");
            });
    });

app/Models/Package.php
<?php

namespace App\Models;

use App\Models\Traits\ModelActive;
use App\Models\Traits\ModelId;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Package extends Model
{
    use HasFactory;
    use ModelId, ModelActive;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'pin_type_id',
        'pin_count',
        'price',
        'bonus_sponsor',
        'bonus_extra',
        'bonus_ro',
        'bonus_upgrade',
        'bonus_package',
        'package_left',
        'package_right',
        'package_bonus',
        'pair_point',
        'get_reward',
        'give_reward',
        'reward_point',
        'is_active',
        'logo',
        'description',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'pin_count' => 'integer',
        'price' => 'float',
        'bonus_sponsor' => 'float',
        'bonus_extra' => 'float',
        'bonus_ro' => 'float',
        'bonus_upgrade' => 'float',
        'bonus_package' => 'boolean',
        'package_left' => 'integer',
        'package_right' => 'integer',
        'pair_point' => 'integer',
        'get_reward' => 'boolean',
        'give_reward' => 'boolean',
        'reward_point' => 'integer',
        'is_active' => 'boolean',
    ];

    // relationship
    public function pinType()
    {
        return $this->belongsTo(PinType::class, 'pin_type_id', 'id')
            ->byType(
                isPackageRequirePIN()
                    ? (PIN_GLOBAL ? PIN_TYPE_GLOBAL : PIN_TYPE_PACKAGE)
                    : PIN_TYPE_PACKAGE
            );
    }
    // relationship:end

    // scope
    public function scopeByName(Builder $builder, string $name): Builder
    {
        return $builder->where('name', '=', $name);
    }

    public function scopeByPlan(Builder $builder, int $plan): Builder
    {
        return $builder->whereHas('pinType', function ($pinType) use ($plan) {
            return $pinType->byPlan($plan);
        });
    }

    public function scopeByStart(Builder $builder): Builder
    {
        return $builder->where('id', '<', TOP_PACKAGE);
    }

    public function scopeByUpgrade(Builder $builder, self|int $current = null): Builder
    {
        $currendId = is_null($current) ? 0 : (($current instanceof self) ? $current->id : $current);

        return $builder->where('id', '>', $currendId);
    }
    // scope:end

    // static
    public static function isRequirePIN()
    {
        return (PACKAGE_USE_PIN && PIN_ENABLED);
    }

    public static function activePackages(int $plan = null): Collection
    {
        $query = static::query()->byActive();

        if (!empty($plan)) {
            $query = $query->byPlan($plan);
        }

        return $query->get();
    }
    // static:end

    // accessor
    public function getActualBonusSponsorAttribute()
    {
        // if (!BONUS_SPONSOR_BY_PACKAGE) {
        //     return BonusSponsor::bonusAmount();
        // }

        return $this->bonus_sponsor;
    }

    public function getActualPriceAttribute()
    {
        return static::isRequirePIN()
            ? $this->pinType->price * $this->pin_count
            : $this->price;
    }

    public function getImageLogoAttribute()
    {
        return asset('assets/images/' . ($this->logo ?? 'logo/logo.png'));
    }
    // accessor:end
}

app/Models/TransPackage.php
<?php

namespace App\Models;

use App\Casts\UppercaseCast;
use App\Models\Traits\ModelCode;
use App\Models\Traits\ModelId;
use App\Models\Traits\ModelTransStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TransPackage extends Model
{
    use HasFactory;
    use ModelId, ModelCode, ModelTransStatus;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'code',
        'seller_id',
        'buyer_id',
        'package_id',
        'pin_count',
        'trans_type',
        'package_price',
        'unique_digit',
        'status',
        'status_at',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'code' => UppercaseCast::class,
        'pin_count' => 'integer',
        'trans_type' => 'integer',
        'package_price' => 'float',
        'unique_digit' => 'integer',
        'status' => 'integer',
        'status_at' => 'datetime',
    ];

    // static
    public static function makeCode(int $type): string
    {
        $typePrefix = ($type == TRANS_PKG_RO)
            ? 'R'
            : (($type == TRANS_PKG_UPGRADE)
                ? 'U' : 'A');

        return $typePrefix . date('ymd') . mt_rand(100001, 999999);
    }

    public static function statusTextAdmin(int $status): string
    {
        // if ($status == TRANS_ORDER) return __('label.status.pending');
        if ($status == TRANS_CONFIRMED) return __('label.status.complete');
        if ($status == TRANS_CANCELED) return __('label.status.canceled');
        if ($status == TRANS_REJECTED) return __('label.status.rejected');

        return __('label.status.confirm');
    }

    public static function statusTextMember(int $status): string
    {
        if ($status == TRANS_CONFIRMED) return __('label.status.complete');
        if ($status == TRANS_CANCELED) return __('label.status.canceled');

        $text = __('label.status.confirm');
        if ($status == TRANS_REJECTED) $text = __('label.status.rejected') . ' / ' . $text;

        return $text;
    }

    public static function statusTextColor(int $status): string
    {
        if ($status == TRANS_ORDER) return 'yellow-700';
        if ($status == TRANS_CONFIRMED) return 'success';
        if ($status == TRANS_CANCELED) return 'red-300';
        if ($status == TRANS_REJECTED) return 'red-300';

        return 'cyan-300';
    }
    // static:end

    // relationship
    public function buyer()
    {
        return $this->belongsTo(User::class, 'buyer_id', 'id');
    }

    public function seller()
    {
        return $this->belongsTo(User::class, 'seller_id', 'id');
    }

    public function package()
    {
        return $this->belongsTo(Package::class, 'package_id', 'id');
    }

    public function bonusRO()
    {
        return $this->hasMany(UserBonus::class, 'ro_id', 'id')->bonusRO();
    }

    public function bonusUpgrade()
    {
        return $this->hasMany(UserBonus::class, 'ro_id', 'id')->bonusUpgrade();
    }

    public function bonusReward()
    {
        return $this->hasOne(UserReward::class, 'ro_id', 'id')->byTransStatus([WD_PROCESSING, WD_COMPLETE]);
    }
    // relationship:end

    // scope
    public function scopeByTransType(Builder $builder, int|array $type): Builder
    {
        if (!is_array($type)) $type = [$type];

        return $builder->whereIn('trans_type', $type);
    }

    public function scopeByStarter(Builder $builder): Builder
    {
        return $builder->byTransType(TRANS_PKG_START);
    }

    public function scopeByUpgrade(Builder $builder): Builder
    {
        return $builder->byTransType(TRANS_PKG_UPGRADE);
    }

    public function scopeByRO(Builder $builder): Builder
    {
        return $builder->byTransType(TRANS_PKG_RO);
    }

    public function scopeByNotRO(Builder $builder): Builder
    {
        return $builder->byTransType([TRANS_PKG_START, TRANS_PKG_UPGRADE]);
    }

    public function scopeByConfirmed(Builder $builder): Builder
    {
        return $builder->byTransStatus(TRANS_CONFIRMED);
    }
    // scope:end

    // accessor
    public function getTransConfirmedAttribute()
    {
        return ($this->status == TRANS_CONFIRMED);
    }

    public function getTransRejectedAttribute()
    {
        return ($this->status == TRANS_REJECTED);
    }

    public function getTransOrderAttribute()
    {
        return ($this->status == TRANS_ORDER);
    }

    public function getTransTransferredAttribute()
    {
        return ($this->status == TRANS_TRANSFERRED);
    }

    public function getTransCancelAttribute()
    {
        return ($this->status == TRANS_CANCELED);
    }

    public function getStatusTextMemberAttribute()
    {
        // if ($this->trans_confirmed) return __('label.status.complete');
        // if ($this->trans_canceled) return __('label.status.canceled');

        // $text = __('label.status.confirm');
        // if ($this->trans_rejected) $text = __('label.status.rejected') . ' / ' . $text;

        // return $text;

        return TransPackage::statusTextMember($this->status);
    }

    public function getStatusTextAdminAttribute()
    {
        // if ($this->trans_order) return __('label.status.pending');
        // if ($this->trans_confirmed) return __('label.status.complete');
        // if ($this->trans_canceled) return __('label.status.canceled');
        // if ($this->trans_rejected) return __('label.status.rejected');

        // return __('label.status.confirm');

        return TransPackage::statusTextAdmin($this->status);
    }

    public function getStatusColorAttribute()
    {
        return TransPackage::statusTextColor($this->status);
    }

    public function getIsCompanySellerAttribute()
    {
        return ($this->seller_id == 0);
    }

    public function getSellerBanksAttribute()
    {
        $seller = !$this->is_company_seller ? $this->seller : User::query()->byId(1)->first();

        return $seller->user_banks;
    }

    public function getIsUpgradeAttribute()
    {
        return ($this->trans_type == TRANS_PKG_UPGRADE);
    }

    public function getIsActivateAttribute()
    {
        return ($this->trans_type == TRANS_PKG_START);
    }

    public function getIsRepeatOrderAttribute()
    {
        return ($this->trans_type == TRANS_PKG_RO);
    }

    public function getSellerNameAttribute()
    {
        if ($this->is_company_seller) {
            return config('app.name');
        }

        return $this->seller->name;
    }

    public function getSellerUsernameAttribute()
    {
        if ($this->is_company_seller) {
            return '';
        }

        return $this->seller->username;
    }

    public function getSellerPhoneAttribute()
    {
        if ($this->is_company_seller) {
            return env('CONTACT_CENTER_PHONE');
        }

        return $this->seller->phone;
    }

    public function getSellerEmailAttribute()
    {
        if ($this->is_company_seller) {
            return env('CONTACT_CENTER_EMAIL');
        }

        return $this->seller->email;
    }

    public function getTransTypeNameAttribute()
    {
        return $this->is_repeat_order
            ? 'Repeat Order'
            : ($this->is_upgrade ? 'Upgrade' : 'Aktivasi');
    }
    // accessor:end
}

app/Models/UserBank.php
<?php

namespace App\Models;

use App\Models\Traits\ModelActive;
use App\Models\Traits\ModelId;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserBank extends Model
{
    use HasFactory;
    use ModelId, ModelActive;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'user_id',
        'bank_id',
        'acc_no',
        'acc_name',
        'is_active',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'is_active' => 'boolean',
    ];

    // relation
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function bank()
    {
        return $this->belongsTo(Bank::class, 'bank_id', 'id');
    }

    public function together()
    {
        return $this->hasMany(static::class, 'acc_no', 'acc_no');
    }
    // relation:end

    // scope
    public function scopeByCompanyBank(Builder $builder): Builder
    {
        return $builder->where('user_id', '=', 0);
    }

    public function scopeByMemberBank(Builder $builder, int $memberId = null): Builder
    {
        $builder = $builder->where('user_id', '>', 0);

        if (!is_null($memberId)) return $builder->where('user_id', '=', $memberId);

        return $builder;
    }
    // scope:end

    // static
    public static function setNewAccount(array $values): void
    {
        $isCompany = ($values['user_id'] == 0);

        if (!$isCompany) {
            static::query()->byMemberBank($values['user_id'])->update(['is_active' => false]);
        }

        $values['is_active'] = true;

        static::create($values);
    }
    // static:end

    // public
    public function setStatus(bool $status): void
    {
        $values = ['is_active' => $status];

        if (!$this->is_company_bank && $status) {
            static::query()->byMemberBank($this->user_id)
                ->where('id', '!=', $this->id)
                ->update(['is_active' => false]);
        }

        $this->update($values);
    }
    // public:end

    // accessor
    public function getBankCodeAttribute()
    {
        return optional($this->bank)->code;
    }

    public function getBankNameAttribute()
    {
        return optional($this->bank)->name;
    }

    public function getIsCompanyBankAttribute()
    {
        return ($this->user_id == 0);
    }

    public function getUserNameAttribute()
    {
        return $this->is_company_bank ? config('app.name') : optional($this->user)->name;
    }
    // accessor:end
}

resources/views/transactions/package/detail-content.blade.php
<div class="row g-2 mb-3">
    <div class="col-12 d-flex flex-nowrap">
        <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.package.title')</div>
        <div class="flex-fill ms-3">{{ $transPackage->package->name }}</div>
    </div>
    <div class="col-12 d-flex flex-nowrap">
        <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">Jenis</div>
        <div class="flex-fill ms-3">{{ $transPackage->is_repeat_order ? 'Repeat Order' : ($transPackage->is_upgrade ? 'Upgrade' : 'Aktivasi') }}</div>
    </div>
    <div class="col-12 d-flex flex-nowrap">
        <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.package.price')</div>
        <div class="flex-fill ms-3">@translate('format.currency.symbol.text') @formatNumber($transPackage->package_price)</div>
    </div>
    <div class="col-12 d-flex flex-nowrap">
        <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.package.unique-digit')</div>
        <div class="flex-fill ms-3">@formatNumber($transPackage->unique_digit)</div>
    </div>
    <div class="col-12 d-flex flex-nowrap">
        <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.package.total-transfer')</div>
        <div class="flex-fill ms-3">@translate('format.currency.symbol.text') @formatNumber($transPackage->package_price + $transPackage->unique_digit)</div>
    </div>
    <div class="col-12 d-flex flex-nowrap">
        <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">Status</div>
        <div class="flex-fill ms-3"><span class="text-{{ $transPackage->status_color }}">{{ $authUser->is_member_user ? $transPackage->status_text_member : $transPackage->status_text_admin }}</span></div>
    </div>
    @if ($authUser->is_member_user && ($transPackage->trans_order || $transPackage->trans_rejected))
        @if ($transPackage->seller_banks->isNotEmpty())
            <div class="col-12 pt-2">
                <div>@translate('text.please-transfer-to'):</div>
                <ol class="mb-0">
                    @foreach ($transPackage->seller_banks as $userBank)
                        <li><span class="fw-bold me-1">{{ $userBank->bank_code }}</span><span class="me-1">-</span><span class="me-1">{{ $userBank->acc_no }}</span><span class="me-1">({{ $userBank->acc_name }})</span></li>
                    @endforeach
                </ol>
            </div>
        @endif
        <div class="col-12 pt-3">
            {!! __('text.confirm-whatsapp', ['whatsapp' => $transPackage->seller_phone]) !!}
        </div>
    @endif
</div>
@if (!$authUser->is_member_user)
    <div class="fw-bold mb-2">@translate('label.member')</div>
    <div class="row g-2">
        <div class="col-12 d-flex flex-nowrap">
            <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.user.name')</div>
            <div class="flex-fill ms-3">{{ $transPackage->buyer->name }}</div>
        </div>
        <div class="col-12 d-flex flex-nowrap">
            <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.user.username')</div>
            <div class="flex-fill ms-3">{{ $transPackage->buyer->username }}</div>
        </div>
        <div class="col-12 d-flex flex-nowrap">
            <div class="flex-shrink-0 d-flex justify-content-between with-semicolon" style="width:40%;">@translate('label.user.phone')</div>
            <div class="flex-fill ms-3">{{ $transPackage->buyer->phone }}</div>
        </div>
    </div>
@endif

resources/views/transactions/package/detail.blade.php
<div class="modal-content">
    @include('partials.modals.modal-header', [
        'modalTitle' => __('header.package.detail')
    ])
    <div class="modal-body">
        @include('transactions.package.detail-content', ['transPackage' => $transPackage])
    </div>
    @include('partials.modals.modal-footer', [
        'modalFoterClass' => 'justify-content-center',
        'modalFooterContent' => [
            view('partials.buttons.close-modal', ['closeText' => __('button.close')])->render()
        ],
    ])
</div>

resources/views/transactions/package/mail-confirm-package.blade.php
@extends('layouts.app-mail')

@section('title', __('header.package.purchase-info', ['attr' => $transPackage->trans_type_name]))

@section('content')
<div style="margin-bottom:1rem;">
    Hi... <span style="font-size:20px; font-weight:600;">{{ $transPackage->buyer->name }}</span> ({{ $transPackage->buyer->username }})
</div>
<div style="margin-bottom: 2rem;">
    @if ($transPackage->is_upgrade)
        {{ __('message.mail.upgraded') . ' ' . __('text.to-be') . ' ' . $transPackage->package->name }}
    @elseif ($transPackage->is_repeat_order)
        @translate('message.mail.repeat-order')
    @else
        {{ __('message.mail.activated') . ' ' . __('text.as') . ' ' . $transPackage->package->name }}
    @endif
</div>
@include('partials.mail.row-space')
<a href="{{ route('welcome') }}">{{ config('app.name') }}</a>
@endsection

resources/views/transactions/package/mail-order-package.blade.php
@extends('layouts.app-mail')

@section('title', __('header.package.purchase-info', ['attr' => $transPackage->trans_type_name]))

@section('content')
@if (in_array($sendTo, ['admin', 'sponsor']))
    @php
        $buyer = $transPackage->buyer;
    @endphp

    @include('partials.mail.rows-header', ['textHeader' => __('label.member') ])
    @include('partials.mail.row', [
        'rowLabel' => __('label.user.name'),
        'rowValue' => "<div>{$buyer->name} ($buyer->username)</div><div>{$buyer->phone}</div>"
    ])
    @include('partials.mail.row-space')
@endif

@php
    $package = $transPackage->package;
    // $packageName = $package->name;
    // $sellerName = $transPackage->seller_name;
    // if (!$transPackage->is_company_seller) {
    //     $sellerName = "{$sellerName} ({$transPackage->seller_username})";
    // }

    // $sellerPhone = $transPackage->seller_phone;
@endphp

@include('partials.mail.rows-header', ['textHeader' => __('label.package.title')])
@include('partials.mail.row', [
    'rowLabel' => __('label.trans-no'),
    'rowValue' => $transPackage->code,
])
@include('partials.mail.row', [
    'rowLabel' => 'Jenis',
    'rowValue' => $transPackage->trans_type_name
])
@include('partials.mail.row', [
    'rowLabel' => __('label.package.name'),
    'rowValue' => $package->name
])
@include('partials.mail.row', [
    'rowLabel' => __('label.package.price'),
    'rowValue' => __('format.currency.symbol.text') . ' ' . formatNumber($transPackage->package_price)
])
@include('partials.mail.row', [
    'rowLabel' => __('label.package.unique-digit'),
    'rowValue' => formatNumber($transPackage->unique_digit)
])
@include('partials.mail.row', [
    'rowLabel' => __('label.package.total-transfer'),
    'rowValue' => __('format.currency.symbol.text') . ' ' . formatNumber($transPackage->package_price + $transPackage->unique_digit)
])
@include('partials.mail.row-space')

@if (!in_array($sendTo, ['admin', 'sponsor']))
    {{-- @include('partials.mail.row', [
        'rowLabel' => __('label.order-to'),
        'rowValue' => "<div>{$sellerName}</div><div>{$sellerPhone}</div>"
    ]) --}}

    @if ($transPackage->seller_banks->isNotEmpty())
        @include('partials.mail.row-space')
        <div>@translate('text.please-transfer-to'):</div>
        <ol>
            @foreach ($transPackage->seller_banks as $userBank)
                <li><span style="font-weight:600; margin-right:5px;">{{ $userBank->bank_code }}</span><span style="margin-right:5px;">-</span><span style="margin-right:5px;">{{ $userBank->acc_no }}</span><span style="margin-right:5px;">({{ $userBank->acc_name }})</span></li>
            @endforeach
        </ol>
    @endif

    @include('partials.mail.row-space')
    <div>{!! __('text.confirm-whatsapp', ['whatsapp' => $transPackage->seller_phone]) !!}</div>
    @include('partials.mail.row-space')
    @include('partials.mail.row-space')
    @include('partials.mail.rows-header', ['textHeader' => config('app.name') ])
@endif
@endsection

resources/views/transactions/package/select-confirm.blade.php
@php
    $btnText = ($type == TRANS_PKG_UPGRADE)
        ? __('button.upgrade')
        : (($type == TRANS_PKG_RO) ? __('button.ro') : __('button.activate'));
@endphp

<form class="modal-content remote-submit" action="{{ $postUrl }}" method="POST" data-alert-container="#alert-form-container">
    @include('partials.modals.modal-header', ['modalTitle' => __('header.confirmation')])
    <div class="modal-body">
        @csrf
        <input type="hidden" name="package_id" value="{{ $package->id }}">
        <div id="alert-form-container"></div>
        <div class="text-center">
            <div class="d-flex justify-content-center align-items-center mb-2">
                <div class="package-logo border-0 rounded-0">
                    <img src="{{ $package->image_logo }}" alt="{{ $package->name }}">
                </div>
            </div>
            <div class="fw-bold mb-2">{{ $package->name }}</div>
            <div class="fw-bold mb-2">{{ __('format.currency.symbol.text') }} @formatNumber($package->actual_price)</div>
            <div class="border-bottom mb-2"></div>
            <div class="fw-bold">@translate('label.benefit'):</div>
            <div>@translate('menu.bonus-sponsor')</div>
            @if ($package->bonus_extra > 0)
                <div>@translate('menu.bonus-extra')</div>
            @endif
            @if ($package->bonus_package && BONUS_PACKAGE_ENABLED)
                <div>@translate('menu.bonus-package')</div>
            @endif
            @if ($package->get_reward)
                <div>@translate('menu.reward')</div>
            @endif
        </div>
    </div>
    @include('partials.modals.modal-footer', [
        'modalFoterClass' => 'justify-content-center',
        'modalFooterContent' => [
            view('partials.buttons.submit', [
                'btnIcon' => 'check',
                'btnText' => $btnText,
                'btnClass' => 'btn-primary btn-pill'
            ])->render(),
        ],
    ])
</form>

resources/views/transactions/package/select.blade.php
@php
    if ($type == TRANS_PKG_UPGRADE) {
        $pageHeading = __('breadcrumb.package.upgrade');
        $btnText = __('button.upgrade');
        $routeName = 'package.upgrade.selected';
    } elseif ($type == TRANS_PKG_RO) {
        $pageHeading = __('breadcrumb.package.ro');
        $btnText = __('button.ro');
        $routeName = 'package.ro.selected';
    } else {
        $pageHeading = __('breadcrumb.package.activate');
        $btnText = __('button.activate');
        $routeName = 'package.activate.selected';
    }
@endphp

@extends('layouts.main')

@section('pageContent')
@include('partials.alert')
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 g-3">
    @foreach ($packages as $package)
        <div class="col d-flex">
            <div class="card flex-fill" style="--bs-card-bg:var(--bs-theme);">
                <div class="card-body text-center d-flex">
                    <div class="flex-fill d-flex flex-column justify-content-between">
                        <div class="mb-3">
                            <div class="d-flex justify-content-center align-items-center mb-2">
                                <div class="package-logo border-0 rounded-0">
                                    <img src="{{ $package->image_logo }}" alt="{{ $package->name }}">
                                </div>
                            </div>
                            <div class="fw-bold mb-2">{{ $package->name }}</div>
                            <div class="fw-bold mb-2">{{ __('format.currency.symbol.text') }} @formatNumber($package->actual_price)</div>
                            <div class="border-bottom mb-2"></div>
                            <div class="fw-bold">@translate('label.benefit'):</div>
                            <div>@translate('menu.bonus-sponsor')</div>
                            @if ($package->bonus_extra > 0)
                                <div>@translate('menu.bonus-extra')</div>
                            @endif
                            @if ($package->bonus_package && BONUS_PACKAGE_ENABLED)
                                <div>@translate('menu.bonus-package')</div>
                            @endif
                            @if ($package->get_reward)
                                <div>@translate('menu.reward')</div>
                            @endif
                        </div>
                        <div>
                            @include('partials.buttons.open-modal', [
                                'btnClass' => 'btn-pill btn-primary px-5',
                                'btnText' => $btnText,
                                'modalUrl' => route($routeName, ['package' => $package->id]),
                                'modalTarget' => '#my-order-package',
                                'isAjaxModal' => true,
                            ])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
</div>
@endsection

@push('topContent')
    @include('partials.modals.modal-sm', ['bsModalId' => 'my-order-package', 'scrollable' => true, 'noEscape' => true])
@endpush

@push('pageCSS')
<style>
    .package-logo {
        --pkg-logo-size: 100px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
        border: 1px solid var(--bs-border-color-translucent);
        border-radius: 50%;
        overflow: hidden;
    }
    .package-logo > img {
        width: var(--pkg-logo-size);
        height: var(--pkg-logo-size);
        line-height: var(--pkg-logo-size);
        text-align: center;
    }
</style>
@endpush